/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2025-03-07 13:28:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>TalentFlow - Plateforme de Recrutement</title>\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    <!-- Google Fonts -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --primary-color: #1e88e5;\r\n");
      out.write("            --secondary-color: #4caf50;\r\n");
      out.write("            --accent-color: #ff5722;\r\n");
      out.write("            --dark-color: #303f9f;\r\n");
      out.write("            --light-color: #f5f5f5;\r\n");
      out.write("            --text-color: #333333;\r\n");
      out.write("            --border-radius: 0.375rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Roboto', sans-serif;\r\n");
      out.write("            color: var(--text-color);\r\n");
      out.write("            background: linear-gradient(135deg, #f8f9fa, #e0e7ff);\r\n");
      out.write("            overflow-x: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.95);\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("        .navbar-brand {\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: var(--primary-color) !important;\r\n");
      out.write("            font-size: 1.8rem;\r\n");
      out.write("            transition: color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        .navbar-brand:hover {\r\n");
      out.write("            color: var(--dark-color) !important;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-link {\r\n");
      out.write("            color: var(--text-color) !important;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            transition: color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-link.active, .nav-link:hover {\r\n");
      out.write("            color: var(--primary-color) !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary {\r\n");
      out.write("            background: linear-gradient(45deg, var(--primary-color), #7986cb);\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 10px 25px;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            transition: transform 0.3s, box-shadow 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-primary:hover {\r\n");
      out.write("            background: var(--dark-color);\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 5px 15px rgba(63, 81, 181, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("        .btn-outline-primary {\r\n");
      out.write("            color: var(--primary-color);\r\n");
      out.write("            border-color: var(--primary-color);\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            transition: all 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-outline-primary:hover {\r\n");
      out.write("            background: var(--primary-color);\r\n");
      out.write("            color: white;\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bg-primary {\r\n");
      out.write("            background: linear-gradient(135deg, var(--primary-color), #7986cb);\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("        .bg-primary::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: -50%;\r\n");
      out.write("            left: -50%;\r\n");
      out.write("            width: 200%;\r\n");
      out.write("            height: 200%;\r\n");
      out.write("            background: radial-gradient(circle, rgba(255, 255, 255, 0.2), transparent);\r\n");
      out.write("            animation: pulse 8s infinite;\r\n");
      out.write("        }\r\n");
      out.write("        .hero-text h1 {\r\n");
      out.write("            font-size: 3.5rem;\r\n");
      out.write("            font-weight: 900;\r\n");
      out.write("            text-shadow: 0 0 15px rgba(255, 255, 255, 0.5);\r\n");
      out.write("            animation: fadeInDown 1s ease-out;\r\n");
      out.write("        }\r\n");
      out.write("        .hero-text p {\r\n");
      out.write("            font-size: 1.4rem;\r\n");
      out.write("            animation: fadeInUp 1.5s ease-out;\r\n");
      out.write("        }\r\n");
      out.write("        .hero-img {\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.2);\r\n");
      out.write("            transform: translateY(20px);\r\n");
      out.write("            animation: float 3s ease-in-out infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card {\r\n");
      out.write("            border-radius: var(--border-radius);\r\n");
      out.write("            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            border: none;\r\n");
      out.write("            transition: transform 0.3s, box-shadow 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        .card:hover {\r\n");
      out.write("            transform: translateY(-10px);\r\n");
      out.write("            box-shadow: 0 10px 25px rgba(0, 0, 0, 0.15);\r\n");
      out.write("        }\r\n");
      out.write("        .card i {\r\n");
      out.write("            transition: transform 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        .card:hover i {\r\n");
      out.write("            transform: scale(1.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .job-card {\r\n");
      out.write("            transition: transform 0.3s, box-shadow 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        .job-card:hover {\r\n");
      out.write("            transform: translateY(-10px);\r\n");
      out.write("            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer {\r\n");
      out.write("            background: linear-gradient(135deg, #343a40, #495057);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 3rem 0;\r\n");
      out.write("            border-top: 2px solid var(--primary-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .modal-content {\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes pulse {\r\n");
      out.write("            0% { transform: scale(1); }\r\n");
      out.write("            50% { transform: scale(1.1); }\r\n");
      out.write("            100% { transform: scale(1); }\r\n");
      out.write("        }\r\n");
      out.write("        @keyframes fadeInDown {\r\n");
      out.write("            from { opacity: 0; transform: translateY(-50px); }\r\n");
      out.write("            to { opacity: 1; transform: translateY(0); }\r\n");
      out.write("        }\r\n");
      out.write("        @keyframes fadeInUp {\r\n");
      out.write("            from { opacity: 0; transform: translateY(50px); }\r\n");
      out.write("            to { opacity: 1; transform: translateY(0); }\r\n");
      out.write("        }\r\n");
      out.write("        @keyframes float {\r\n");
      out.write("            0% { transform: translateY(20px); }\r\n");
      out.write("            50% { transform: translateY(0); }\r\n");
      out.write("            100% { transform: translateY(20px); }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Navigation -->\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-white shadow-sm sticky-top\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"index.html\">\r\n");
      out.write("            <i class=\"fas fa-briefcase me-2\"></i>TalentFlow\r\n");
      out.write("        </a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\"\r\n");
      out.write("                aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("            <ul class=\"navbar-nav me-auto\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link active\" href=\"index.html\">Accueil</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"offres-emploi.jsp\">Offres d'emploi</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div>\r\n");
      out.write("                <button class=\"btn btn-outline-primary me-2\">Connexion</button>\r\n");
      out.write("                <button class=\"btn btn-primary\">Inscription</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- Main Content Area -->\r\n");
      out.write("<div id=\"page-content\">\r\n");
      out.write("    <section id=\"home-content\">\r\n");
      out.write("        <div class=\"bg-primary text-white py-5\">\r\n");
      out.write("            <div class=\"container py-5\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"col-lg-6 hero-text\">\r\n");
      out.write("                        <h1 class=\"display-4 fw-bold mb-4\">Simplifiez votre recrutement avec TalentFlow</h1>\r\n");
      out.write("                        <p class=\"lead mb-4\">La plateforme qui connecte les meilleurs talents avec les entreprises qui recrutent.</p>\r\n");
      out.write("                        <div class=\"d-flex gap-3\">\r\n");
      out.write("                            <a href=\"register.html?type=candidate\" class=\"btn btn-light btn-lg\">Je cherche un emploi</a>\r\n");
      out.write("                            <a href=\"register.html?type=recruiter\" class=\"btn btn-outline-light btn-lg\">Je recrute</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                        <img src=\"https://cdn.aarp.net/content/dam/aarp/work/job-search/2020/08/1140-new-job-keyboard.jpg\" alt=\"Recrutement\" class=\"img-fluid hero-img\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container py-5\">\r\n");
      out.write("            <h2 class=\"text-center mb-5 fw-bold text-primary\">Pourquoi choisir TalentFlow ?</h2>\r\n");
      out.write("            <div class=\"row g-4\">\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"card h-100 text-center p-4\">\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <i class=\"fas fa-tachometer-alt text-primary\" style=\"font-size: 3rem;\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3 class=\"h5\">Processus simplifié</h3>\r\n");
      out.write("                        <p class=\"text-muted\">Gérez efficacement toutes les étapes du recrutement avec notre interface intuitive.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"card h-100 text-center p-4\">\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <i class=\"fas fa-search text-primary\" style=\"font-size: 3rem;\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3 class=\"h5\">Trouvez les meilleurs talents</h3>\r\n");
      out.write("                        <p class=\"text-muted\">Accédez à une base de candidats qualifiés pour votre entreprise.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"card h-100 text-center p-4\">\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <i class=\"fas fa-lock text-primary\" style=\"font-size: 3rem;\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3 class=\"h5\">Sécurité et confidentialité</h3>\r\n");
      out.write("                        <p class=\"text-muted\">Vos données sont protégées avec les standards de sécurité les plus élevés.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container py-5\">\r\n");
      out.write("            <div class=\"row justify-content-center\">\r\n");
      out.write("                <div class=\"col-lg-10\">\r\n");
      out.write("                    <div class=\"card bg-primary text-white p-5 text-center\">\r\n");
      out.write("                        <h2 class=\"mb-4 fw-bold\">Prêt à transformer votre processus de recrutement ?</h2>\r\n");
      out.write("                        <p class=\"lead mb-4\">Rejoignez TalentFlow dès aujourd'hui et trouvez les talents qui feront la différence.</p>\r\n");
      out.write("                        <div class=\"d-flex justify-content-center gap-3\">\r\n");
      out.write("                            <a href=\"register.html?type=recruiter\" class=\"btn btn-light\">Espace recruteur</a>\r\n");
      out.write("                            <a href=\"register.html?type=candidate\" class=\"btn btn-outline-light\">Espace candidat</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"footer text-center text-lg-start\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-6 mb-4 mb-lg-0\">\r\n");
      out.write("                <h5 class=\"text-uppercase mb-3\">TalentFlow</h5>\r\n");
      out.write("                <p>Simplifiez le recrutement et trouvez les meilleurs talents avec notre plateforme.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 mb-4 mb-lg-0\">\r\n");
      out.write("                <h5 class=\"text-uppercase mb-3\">Liens rapides</h5>\r\n");
      out.write("                <ul class=\"list-unstyled\">\r\n");
      out.write("                    <li><a href=\"index.html\">Accueil</a></li>\r\n");
      out.write("                    <li><a href=\"job-listings.html\">Offres d'emploi</a></li>\r\n");
      out.write("                    <li><a href=\"login.html\">Connexion</a></li>\r\n");
      out.write("                    <li><a href=\"register.html\">Inscription</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3\">\r\n");
      out.write("                <h5 class=\"text-uppercase mb-3\">Contact</h5>\r\n");
      out.write("                <ul class=\"list-unstyled\">\r\n");
      out.write("                    <li><i class=\"fas fa-envelope me-2\"></i>contact@talentflow.fr</li>\r\n");
      out.write("                    <li><i class=\"fas fa-phone me-2\"></i>+33 1 23 45 67 89</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"text-center mt-4\">\r\n");
      out.write("            <p>© 2025 TalentFlow by Noobs. Tous droits réservés.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
